# Generated by Django 3.0.2 on 2020-01-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_at',
        ),
    ]
