# Generated by Django 3.0.2 on 2020-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0003_remove_submission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.CharField(default='0%', max_length=10),
            preserve_default=False,
        ),
    ]
